### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by EL2022-2** [pschatzmann/esp32_radio#34]
esp32_radio-master\esp32-radio\Radio.cpp: In member function 'void Radio::startBluetooth()':
Radio.cpp:35:17: error: 'class BlootoothA2DSink' has no member named 'set_on_data_received'
       a2d_sink->set_on_data_received(recordActivity);

**Comment by pschatzmann** [comment]
I could not reproduce your issue, but I found quite some other issues which prevented the Arduino code from compiling, which I have corrected.

Are you sure that you have a recent version of https://github.com/pschatzmann/ESP32-A2DP installed ?

**Comment by EL2022-2** [comment]
The following is translated by Google
          Hi mr pschatzmann, great to hear from you and update on esp32-radio. I changed to ESP8266Audio-1.9.5 to build normally, but the sound is still not normal, the sound of explosion
!
![16](https://user-images.githubusercontent.com/108987033/178156959-ee712e25-09ff-4299-86ed-a19df03f3448.png)

![08](https://user-images.githubusercontent.com/108987033/178157397-ee53ca69-bd0f-40aa-afe0-58bb027ebf7a.JPG)
.

**Comment by pschatzmann** [comment]
Which DAC are you using ? 
I haven't used the ESP8266Audio for a long time and prefer to use my Arduino Audio Tools now...

**Comment by EL2022-2** [comment]
Using the TDA1387, works great on KaRadio32, building your esp32-radio with the ESP8266Audio library doesn't work ideally.
    I have a new idea now, install ESP32/Vue on the router, and use (instant="http://your url" : instant play a site) command to transmit the URL to KaRadio32.
